### ISSUE TITLE
Removing code results in "ReferenceError: Stats is not defined"

### ISSUE THREAD

**Issue by ruemic** [screepers/screeps-stats#2]
I commenting out 

```
// var ScreepsStats = require('screepsstats')
// global.Stats = new ScreepsStats()
```

and 

```
//  Stats.runBuiltinStats()
```

which results in this error every tick

```
_console1466737246270_0:1
Stats.removeTick(["11413454","11413453"]);
^
ReferenceError: Stats is not defined
```

So I guess this has to do with some sort of internal global caching.
After waiting for a few minutes hoping for this to sort themselves out, I still get the error, I also tried things like setting `global.Stats = undefined` but didn't have any luck with that either. 

Anyone have an idea of whats going on with this?

**Comment by tedivm** [comment]
Yeah- even if you aren't running the built in stats function you need to leave the Stats class available until all the processed ticks have been cleaned out. This is a sign that there are still stats in memory that the stats runner program is reading, but when it tries to delete them with the Stats class it's failing to do so.

**Comment by ruemic** [comment]
makes sense, thx
