### ISSUE TITLE
Re-authorization not done after a server restart.

### ISSUE THREAD

**Issue by DissiNL** [screepers/screeps-stats#6]
Was reported in the slack channel.

Regards,
Dissi

7/11/2016 4:17:17 AM    self.run()
7/11/2016 4:17:17 AM  File "/screeps-stats/screeps_etl/memorystats.py", line 35, in run
7/11/2016 4:17:17 AM    screeps = self.getScreepsAPI()
7/11/2016 4:17:17 AM  File "/screeps-stats/screeps_etl/memorystats.py", line 25, in getScreepsAPI
7/11/2016 4:17:17 AM    self.**api = screepsapi.API(u=settings['screeps_username'],p=settings['screeps_password'],ptr=settings['screeps_ptr'])
7/11/2016 4:17:17 AM  File "/screeps-stats/src/screepsapi/screepsapi/screepsapi.py", line 38, in __init**
7/11/2016 4:17:17 AM    self.token = self.post('auth/signin', email=u, password=p)['token']
7/11/2016 4:17:17 AMKeyError: 'token'
7/11/2016 4:17:18 AMProcess APIProcess-401:
7/11/2016 4:17:18 AMTraceback (most recent call last):

**Comment by DissiNL** [comment]
Full trace in 
http://pastebin.com/raw/xKihK2GZ

**Comment by tedivm** [comment]
Is this still an issue for you? I haven't encountered it in awhile.

**Comment by DissiNL** [comment]
Seems to have been fixed.
